[theme]
base = "light"
primaryColor = "#A3B18E"
backgroundColor = "#FAF6EC"
secondaryBackgroundColor = "#F3EDE0"
textColor = "#2C3531"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
